import Nav from "./components/Nav";
import "./globals.css";
import { Inter } from "next/font/google";
import ThemesProvider from "../app/providers/ThemeProvider.js";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`  min-h-screen  min-w-full
        ${inter.className}`}
      >
        <ThemesProvider>
          <Nav />
          <div className="bg-main">test</div>
          {children}
        </ThemesProvider>
      </body>
    </html>
  );
}
